name: Add issue to Hermes Console Feedback Tracker

on:
  issues:
    types: [opened]

jobs:
  add-to-project:
    runs-on: ubuntu-latest
    if: ${{ vars.HERMES_CONSOLE_PROJECT_URL != '' }}
    steps:
      - uses: actions/add-to-project@v1.0.2
        with:
          project-url: ${{ vars.HERMES_CONSOLE_PROJECT_URL }}
          github-token: ${{ secrets.ADD_TO_PROJECT_PAT }}
